### PR TITLE
Fix for object is not extensible

### LINKED ISSUE #18: I'm getting  error after update HA to 2021.6.x
image

### PR DESCRIPTION
**Pull request by LEJOUI**
Thought the latest PR #13 had all the fixes.
There were some more changes necessary but I didn’t pushed them into the PR.

This wil fix #18 

Will await some conformation if it works.

### CODE REVIEW

File: light-entity-row.js [hunk 1]
```diff
@@ -162,19 +172,17 @@ class AdjustableLightEntityRow extends Polymer.Element {
...
 
     const checkServiceRegexp = /^(light|group)\./
     if (!checkServiceRegexp.test(config.entity)) {
       throw new Error(`invalid entity ${config.entity}`)
     }
-    
+
     this._config = JSON.parse(JSON.stringify(config));
-    this._config.buttons = config.buttons || []
+    this._buttons = JSON.parse(JSON.stringify(config.buttons))
```
Comment (spacegaier) [inline light-entity-row.js:184]:
```suggestion
    if (config.buttons) { 
        this._buttons = JSON.parse(JSON.stringify(config.buttons))
    }
```

Comment (LEJOUI) [reply light-entity-row.js]: thanks!
